name: dailyculture
description: "DailyCulture project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Notificaciones modernas
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
