name: Build and deploy Python app to Azure Web App - DailyCulture

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: DailyCulture
  AZURE_WEBAPP_PACKAGE_PATH: backend
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Comprobación rápida de dependencias (opcional, útil para fallar pronto)
      - name: Install dependencies (from backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Empaquetamos SOLO el backend como artefacto
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: |
            backend/**
            !backend/__pycache__/**
            !backend/.venv/**
            !backend/local.db
            !backend/*.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA7B412A56E24DCCB36FBD59E75DC8EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9DBF2713094D4FE6B1002A2DBF411018 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F32C1B6A2124A84B52CF0DFEB1F55FC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
